# Generated by Django 5.0.1 on 2024-03-02 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="topicobj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("op1", models.CharField(max_length=5000)),
                ("op2", models.CharField(max_length=5000)),
                ("op3", models.CharField(max_length=5000)),
                ("op4", models.CharField(max_length=5000)),
                (
                    "answer",
                    models.CharField(
                        choices=[
                            ("op1", "Op1"),
                            ("op2", "Op2"),
                            ("op3", "Op3"),
                            ("op4", "Op4"),
                        ],
                        max_length=5000,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.PositiveIntegerField()),
                ("noofparticipants", models.PositiveIntegerField()),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="classparticipants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "classroomid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studypal.classroom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=5000)),
                ("description", models.CharField(max_length=5000)),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="courseenrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studypal.courses",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="objanssheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        choices=[
                            ("op1", "Op1"),
                            ("op2", "Op2"),
                            ("op3", "Op3"),
                            ("op4", "Op4"),
                        ],
                        max_length=5000,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studypal.topicobj",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="topics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=5000)),
                ("description", models.CharField(max_length=5000)),
                ("content", models.TextField()),
                ("video_file", models.FileField(upload_to="videos")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studypal.courses",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="topicsquiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=5000)),
                (
                    "questiontype",
                    models.CharField(
                        choices=[("objective", "Objective"), ("theory", "Theory")],
                        max_length=5000,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studypal.topics",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="topicobj",
            name="objquestion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="studypal.topicsquiz"
            ),
        ),
        migrations.CreateModel(
            name="theoryanssheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studypal.topicsquiz",
                    ),
                ),
            ],
        ),
    ]
