# Generated by Django 5.0.1 on 2024-03-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0002_lecturers_alter_courses_lecturer_teachers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturers",
            name="proofofqualific",
            field=models.ImageField(
                default="default.jpg",
                upload_to="qualifications",
                verbose_name="Proof Of Qualifications",
            ),
        ),
    ]
