# Generated by Django 5.0.1 on 2024-03-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0003_alter_lecturers_proofofqualific"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicobj",
            name="answer",
            field=models.CharField(
                choices=[
                    ("op1", "Op1"),
                    ("op2", "Op2"),
                    ("op3", "Op3"),
                    ("op4", "Op4"),
                ],
                max_length=5000,
                verbose_name="Correct Option/Answer",
            ),
        ),
    ]
