# Generated by Django 5.0.1 on 2024-03-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0004_alter_topicobj_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="objanssheet",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
