# Generated by Django 5.0.1 on 2024-03-04 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0005_objanssheet_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="objanssheet",
            old_name="answer",
            new_name="answerfilled",
        ),
    ]
