# Generated by Django 5.0.1 on 2024-03-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0006_rename_answer_objanssheet_answerfilled"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachers",
            name="handlesize",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
