# Generated by Django 5.0.1 on 2024-03-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0007_teachers_handlesize"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="teacher",
        ),
        migrations.AlterField(
            model_name="teachers",
            name="handlesize",
            field=models.PositiveIntegerField(
                default=3, verbose_name="size of class you can handle"
            ),
        ),
        migrations.DeleteModel(
            name="classparticipants",
        ),
        migrations.DeleteModel(
            name="classroom",
        ),
    ]
