# Generated by Django 5.0.1 on 2024-03-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0011_remove_classroom_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseenrollment",
            name="tutored",
            field=models.BooleanField(default=False),
        ),
    ]
