# Generated by Django 5.0.1 on 2024-03-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0012_courseenrollment_tutored"),
    ]

    operations = [
        migrations.CreateModel(
            name="subtitles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtitle", models.FileField(upload_to="srt_files/")),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studypal.topics",
                    ),
                ),
            ],
        ),
    ]
