# Generated by Django 5.0.1 on 2024-03-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0014_userpreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="font_color",
            field=models.CharField(default="#ffffff", max_length=10),
        ),
    ]
