# Generated by Django 5.0.1 on 2024-03-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0015_userpreferences_font_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="font_color",
            field=models.CharField(default="#000000", max_length=10),
        ),
    ]
