# Generated by Django 5.0.1 on 2024-03-17 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0017_userpreferences_word_spacing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="student",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="teacher",
        ),
        migrations.DeleteModel(
            name="classparticipants",
        ),
        migrations.DeleteModel(
            name="classroom",
        ),
        migrations.DeleteModel(
            name="Teachers",
        ),
    ]
