# Generated by Django 5.0.1 on 2024-03-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0018_remove_classroom_student_remove_classroom_teacher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="coverimage",
            field=models.ImageField(default="default.jpg", upload_to="course_pics"),
        ),
        migrations.AddField(
            model_name="topics",
            name="coverimage",
            field=models.ImageField(default="default.jpg", upload_to="topic_pics"),
        ),
    ]
