# Generated by Django 5.0.1 on 2024-03-21 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0019_courses_coverimage_topics_coverimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=5000)),
                ("description", models.CharField(max_length=5000)),
                ("content", models.TextField()),
                ("video_file", models.FileField(upload_to="section_videos")),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studypal.topics",
                    ),
                ),
            ],
        ),
    ]
