# Generated by Django 5.0.1 on 2024-03-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0020_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="coverimage",
            field=models.ImageField(default="default.jpg", upload_to="section_pics"),
        ),
    ]
