# Generated by Django 5.0.1 on 2024-03-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0021_section_coverimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicsquiz",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
