# Generated by Django 5.0.1 on 2024-03-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0022_topicsquiz_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="topics",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
