# Generated by Django 5.0.1 on 2024-03-24 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studypal", "0023_topics_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecturers",
            name="proofofqualific",
        ),
        migrations.RemoveField(
            model_name="lecturers",
            name="qualifications",
        ),
    ]
