# Generated by Django 5.0.1 on 2024-03-01 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="disabilityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="profile_pics"),
                ),
                ("grade", models.CharField(blank=True, max_length=5000, null=True)),
                ("age", models.CharField(max_length=5000)),
                ("phonenumber", models.CharField(max_length=5000)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=5000,
                    ),
                ),
                ("disablities", models.CharField(max_length=5000)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="samaritanProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="profile_pics"),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="what is your class if your in se or primary /level for Uni/poly students",
                        max_length=5000,
                        null=True,
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        help_text="if not school in  but currently employed state our craft",
                        max_length=5000,
                        null=True,
                    ),
                ),
                ("age", models.CharField(max_length=5000)),
                ("address", models.CharField(blank=True, max_length=5000, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=5000,
                    ),
                ),
                ("phonenumber", models.CharField(max_length=5000)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
