# Generated by Django 5.0.1 on 2024-03-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="disabilityprofile",
            old_name="disablities",
            new_name="disabilities",
        ),
        migrations.AlterField(
            model_name="disabilityprofile",
            name="grade",
            field=models.CharField(
                blank=True,
                help_text="what is your class if your in sec or primary /level for Uni or Poly students, Enter respctively",
                max_length=5000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="samaritanprofile",
            name="grade",
            field=models.CharField(
                blank=True,
                help_text="what is your class if your in sec or primary /level for Uni or Poly students, Enter Respectively",
                max_length=5000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="samaritanprofile",
            name="occupation",
            field=models.CharField(
                blank=True,
                help_text="if not in school but currently employed state your craft",
                max_length=5000,
                null=True,
            ),
        ),
    ]
