# Generated by Django 5.0.1 on 2024-03-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_disablities_disabilityprofile_disabilities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="disabilityprofile",
            name="city",
            field=models.CharField(default="Ibadan", max_length=5000),
        ),
        migrations.AddField(
            model_name="disabilityprofile",
            name="state",
            field=models.CharField(default="Oyo State", max_length=5000),
        ),
    ]
